name: Go Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.2.3)
    branches:
      - main  # Trigger on push to main branch as well
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.2.3'  # Default tag name

permissions:
  contents: write  # Allow writing to GitHub releases

env:
  PROJECT_NAME: ${{ github.event.repository.name }}
  BUILD_DATE: ${{ github.run_id }}
  VERSION: ${{ github.ref_name }}  # Dynamic version based on the tag name
  RELEASE_DIR: release

jobs:
  # Linux build job
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full git history for versioning

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pkg-config gcc-aarch64-linux-gnu

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'  # Use Go version from go.mod
          cache: true  # Enable dependency caching

      - name: Get dependencies
        run: |
          export GOPROXY=direct
          export GONOSUMDB=*
          go mod tidy

      - name: Prepare Release Directory
        run: mkdir -p ${{ env.RELEASE_DIR }}

      # Build Linux AMD64
      - name: Build Linux AMD64
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
            -ldflags="-X 'main.Version=${{ env.VERSION }}' -X 'main.BuildDate=${{ env.BUILD_DATE }}'" \
            -o ${{ env.RELEASE_DIR }}/${{ env.PROJECT_NAME }}_linux_amd64

  # Windows build job
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    needs: build-linux  # Ensure Linux build completes first
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full git history for versioning

      # Set up Go for Windows
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'  # Use Go version from go.mod
          cache: true  # Enable dependency caching

      - name: Get dependencies
        run: |
          set GOPROXY=direct
          set GONOSUMDB=*
          go mod tidy

      - name: Prepare Release Directory
        run: mkdir -p ${{ env.RELEASE_DIR }}

      # Build Windows AMD64
      - name: Build Windows AMD64
        run: |
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build \
            -ldflags="-X 'main.Version=${{ env.VERSION }}' -X 'main.BuildDate=${{ env.BUILD_DATE }}'" \
            -o ${{ env.RELEASE_DIR }}/${{ env.PROJECT_NAME }}_windows_amd64.exe

  # Create release on GitHub
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Release Directory
        run: mkdir -p ${{ env.RELEASE_DIR }}

      # Create Source Code Tarball
      - name: Create Source Code Tarball
        run: |
          tar -czvf ${{ env.RELEASE_DIR }}/${{ env.PROJECT_NAME }}_${{ env.BUILD_DATE }}_source.tar.gz \
          --exclude=.git \
          --exclude=${{ env.RELEASE_DIR }} \
          .

      # Create Source Code Zip
      - name: Create Source Code Zip
        run: |
          zip -r ${{ env.RELEASE_DIR }}/${{ env.PROJECT_NAME }}_${{ env.BUILD_DATE }}_source.zip \
          . \
          -x .git\* \
          -x release\*

      # Generate SHA256 Checksums
      - name: Generate SHA256 Checksums
        run: |
          cd ${{ env.RELEASE_DIR }}
          sha256sum * > ${{ env.PROJECT_NAME }}_${{ env.BUILD_DATE }}_checksums.txt

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.RELEASE_DIR }}/*
          generate_release_notes: true  # Auto-generate release notes
          draft: false  # Do not create a draft release
          prerelease: false  # Do not mark as a pre-release
          tag_name: ${{ env.VERSION }}  # Use dynamic version from the tag
