name: Go Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (比如 v1.2.3)
    branches:
      - main  # 在主分支的推送时也触发
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.2.3'  # 默认版本号

permissions:
  contents: write  # Allow writing to GitHub releases

env:
  PROJECT_NAME: ${{ github.event.repository.name }}
  BUILD_DATE: ${{ github.run_id }}
  VERSION: 'v2.0.0-beta.3'  # 固定版本号
  RELEASE_DIR: release

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 Git 历史

      # 安装必要依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pkg-config gcc-aarch64-linux-gnu

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'  # 使用 go.mod 文件指定 Go 版本
          cache: true  # 启用依赖缓存

      - name: Get dependencies
        run: | # 这里使用直连主要防止傻逼代理服务器拉取的不是最新依赖导致相同版本hash不同问题
          export GOPROXY=direct
          export GONOSUMDB=*
          go mod tidy

      - name: Prepare Release Directory
        run: mkdir -p ${{ env.RELEASE_DIR }}

      # Build steps for different platforms
      - name: Build Linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build \
            -ldflags="-X 'main.Version=${{ env.VERSION }}' -X 'main.BuildDate=${{ env.BUILD_DATE }}'" \
            -o ${{ env.RELEASE_DIR }}/${{ env.PROJECT_NAME }}_${{ env.BUILD_DATE }}_linux_arm64

      # Create Source Code Tarball
      - name: Create Source Code Tarball
        run: |
          tar -czvf ${{ env.RELEASE_DIR }}/${{ env.PROJECT_NAME }}_${{ env.BUILD_DATE }}_source.tar.gz \
          --exclude=.git \
          --exclude=${{ env.RELEASE_DIR }} \
          .

      # Create Source Code Zip
      - name: Create Source Code Zip
        run: |
          zip -r ${{ env.RELEASE_DIR }}/${{ env.PROJECT_NAME }}_${{ env.BUILD_DATE }}_source.zip \
          . \
          -x .git\* \
          -x release\*

      # Generate SHA256 Checksums
      - name: Generate SHA256 Checksums
        run: |
          cd ${{ env.RELEASE_DIR }}
          sha256sum * > ${{ env.PROJECT_NAME }}_${{ env.BUILD_DATE }}_checksums.txt

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.RELEASE_DIR }}/*
          generate_release_notes: true  # 自动生成发行说明
          draft: false  # 不创建草稿
          prerelease: false  # 不标记为预发布
          tag_name: ${{ env.VERSION }}  # 使用固定版本号作为发布标签